# Generated by Django 2.2.3 on 2019-07-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
