# Generated by Django 2.1.8 on 2019-09-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(default='', max_length=32, unique=True)),
                ('activity_name', models.CharField(default='', max_length=256)),
                ('begindate', models.TextField(default='')),
                ('enddate', models.TextField(default='')),
                ('institution', models.TextField(default='[]')),
                ('minutes', models.TextField(default='')),
                ('name', models.TextField(default='[]')),
                ('picInfo', models.TextField(default='{}')),
                ('item', models.TextField(default='')),
                ('project', models.TextField(default='')),
            ],
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_id', 'activity_name', 'begindate'], name='apis_activi_activit_59ff66_idx'),
        ),
    ]
