# Generated by Django 2.1.8 on 2019-09-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='pics',
            field=models.TextField(default='[]'),
        ),
    ]
