# Generated by Django 2.1.8 on 2019-09-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_activity_pics'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activity',
            name='apis_activi_activit_59ff66_idx',
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_id', 'activity_name', 'begindate', 'pics'], name='apis_activi_activit_dfe3b7_idx'),
        ),
    ]
